''' 
    Syntax and Semantic Analyzer (Parser & Symbol Table)
    The Parser takes the list of tokens generated by the Lexer and simultaneously verifies 
    both the grammatical structure of the language (using a Recursive Descent strategy) 
    and its semantic validity.

        1) Syntactic Matching: Each grammatical rule (declarations, assignments, if/for loops, and 
           expressions) is mapped to a specific method. The parser uses pointers and lookahead functions 
           (peek, check, match) to validate the current token against what is expected by the grammar.
           If valid, it consumes the token and advances.

        2) Symbol Table & Scope: As the syntax is validated, the SymbolTable tracks the 
           lifecycle of every identifier. It handles nested scopes and records crucial metadata for 
           variables and functions: data type, exact declaration coordinates, initialization status, 
           assigned values, and usage references.

        3) Semantic Validation: The parser enforces logical rules across mathematical and relational 
           operations. It checks for type compatibility (including implicit widening coercions, like 
           int to float), prevents the use of undeclared variables, and issues Semantic Warnings for 
           bad practices (e.g., uninitialized variables, unused declarations, or unreachable code).

        4) Error Recovery (Panic Mode): If a token violates the grammatical rules, a SyntaxError is raised. 
           Instead of crashing the entire compiler, the synchronize() method is triggered. It discards 
           problematic tokens until it finds a safe synchronization point, allowing the parser to catch
           and report multiple syntactic and semantic errors in a single run.
'''

class SyntaxError(Exception):
    pass

class SymbolTable:
    def __init__(self):
        self.scopes = [{}] 
        self.warnings = []
        self.all_symbols = [] 

    def enter_scope(self):
        self.scopes.append({})

    def exit_scope(self):
        current_scope = self.scopes.pop()

        for name, info in current_scope.items():
            if not info['used'] and info['type'] != 'function':
                self.warnings.append(f"Aviso Semântico [Linha {info['decl_line']}]: Variável '{name}' declarada, mas nunca utilizada.")

    def declare(self, name, var_type, line, col, is_function=False):
        current_scope = self.scopes[-1]

        if name in current_scope:
            return False 
        
        symbol_info = {
            'name': name,
            'type': var_type,
            'initialized': is_function, 
            'init_pos': ' ',
            'value': ' ',      
            'used': False,
            'decl_line': line,   
            'decl_col': col,     
            'scope_level': len(self.scopes) - 1
        }

        current_scope[name] = symbol_info
        self.all_symbols.append(symbol_info)

        return True

    #Goes through all scopes from innermost to outermost to find the symbol
    def lookup(self, name):
        for scope in reversed(self.scopes):
            if name in scope:
                return scope[name]
            
        return None

class Parser:
    def __init__(self, tokens):
        self.tokens = tokens
        self.current = 0
        self.errors = []               
        self.semantic_errors = []      
        self.symtab = SymbolTable()    

    def peek_lookahead(self):
        if self.current < len(self.tokens): return self.tokens[self.current]
        return None

    def previous(self):
        return self.tokens[self.current - 1]

    def is_end_token_list(self):
        return self.current >= len(self.tokens)

    def advance(self): #advance pointer and return previous token
        if not self.is_end_token_list(): self.current += 1

        return self.previous()

    
    def check(self, token_class, lexeme=None):
        if self.is_end_token_list(): return False

        token = self.peek_lookahead()
        
        target_class = 'RESERVED_WORD' if token_class == 'KEYWORD' else token_class
        
        if lexeme: #checks if lexeme and class match
            return (token['class'].upper() == token_class.upper() or token['class'].upper() == target_class) and token['lexeme'] == lexeme
        
        return token['class'].upper() == token_class.upper() or token['class'].upper() == target_class


    def match(self, token_class, lexeme=None):
        if self.check(token_class, lexeme):
            self.advance()
            return True
        
        return False

    def consume(self, token_class, lexeme, message):
        if self.check(token_class, lexeme): return self.advance()

        token = self.peek_lookahead()
        
        if token:
            error_msg = f"Erro Sintático [Linha {token['line']}, Col {token['column']}]: Esperava '{lexeme if lexeme else token_class}', mas encontrou '{token['lexeme']}'. {message}"
        else:
            error_msg = f"Erro Sintático: Fim de arquivo inesperado. Esperava '{lexeme if lexeme else token_class}'. {message}"
        
        self.errors.append(error_msg)

        raise SyntaxError()

    def synchronize(self): #try to find synchronization point
        self.advance()

        while not self.is_end_token_list():
            if self.previous()['lexeme'] == ';': return

            current_token = self.peek_lookahead()

            if current_token and current_token['lexeme'] in ['int', 'float', 'char', 'string', 'bool', 'if', 'for', 'return']:
                return
            
            self.advance()

    # SEMANTIC ANALYSIS: TYPE CHECKING
    def check_type_compatibility(self, left_type, operator, right_type, line):
        if left_type == 'unknown' or right_type == 'unknown': return 'unknown'
        
        if operator in ['+', '-', '*', '/']: #Allows implicit int to float promotion
            if left_type in ['int', 'float'] and right_type in ['int', 'float']:
                return 'float' if 'float' in [left_type, right_type] else 'int'
            
            self.semantic_errors.append(f"Erro Semântico [Linha {line}]: Operação '{operator}' inválida entre '{left_type}' e '{right_type}'.")

            return 'unknown'
            
        if operator in ['>', '<', '>=', '<=', '==', '!=']: #Allows comparisons between same types and numeric types
            if left_type == right_type or (left_type in ['int', 'float'] and right_type in ['int', 'float']): return 'bool'

            self.semantic_errors.append(f"Erro Semântico [Linha {line}]: Comparação '{operator}' inválida entre '{left_type}' e '{right_type}'.")

            return 'unknown'
            
        if operator in ['&&', '||']: #Only allows boolean logic between bools, but also allows int as a common C-like flexibility 
            if left_type in ['bool', 'int'] and right_type in ['bool', 'int']: return 'bool'
            
            self.semantic_errors.append(f"Erro Semântico [Linha {line}]: Operador '{operator}' requer booleanos.")
            
            return 'unknown'
            
        return 'unknown'

    def parse(self):
        self.current = 0
        self.errors = []
        self.semantic_errors = []

        while not self.is_end_token_list():
            try:
                self.statement()

            except SyntaxError:
                self.synchronize()
        
        self.symtab.exit_scope() #Final scope exit to check for unused variables in global scope

        return {
            'syntax_errors': self.errors,
            'semantic_errors': self.semantic_errors,
            'semantic_warnings': self.symtab.warnings,
            'symbol_table': self.symtab.all_symbols
        }

    def statement(self):
        if self.check('KEYWORD', 'int') or self.check('KEYWORD', 'float') or \
           self.check('KEYWORD', 'char') or self.check('KEYWORD', 'string') or \
           self.check('KEYWORD', 'bool'):
            self.declaration_or_function()

        elif self.check('KEYWORD', 'if'): 
            self.if_statement()

        elif self.check('KEYWORD', 'for'): 
            self.for_statement()

        elif self.check('KEYWORD', 'return'): 
            self.return_statement()

        elif self.check('DELIMITER', '{'): 
            self.block()

        else: self.assignment_or_expr()

    def declaration_or_function(self):
            self.advance() 
            var_type = self.previous()['lexeme']
            
            self.consume('IDENTIFIER', None, "Esperado nome do identificador após o tipo.")

            var_token = self.previous() 
            var_name = var_token['lexeme']
            var_line = var_token['line']
            var_col = var_token['column']

            if self.match('DELIMITER', '('):
                if not self.symtab.declare(var_name, var_type, var_line, var_col, is_function=True): 
                    self.semantic_errors.append(f"Erro Semântico [Linha {var_line}]: Função '{var_name}' já declarada.")
                
                self.symtab.enter_scope() #Function scope

                if not self.check('DELIMITER', ')'):
                    while True:
                        if self.check('KEYWORD', 'int') or self.check('KEYWORD', 'float') or self.check('KEYWORD', 'string') or self.check('KEYWORD', 'char') or self.check('KEYWORD', 'bool'):
                            self.advance() 
                            param_type = self.previous()['lexeme']
                            
                            self.consume('IDENTIFIER', None, "Esperado nome do parâmetro.")
                            param_token = self.previous()
                            
                            self.symtab.declare(param_token['lexeme'], param_type, param_token['line'], param_token['column'])
                            symbol_param = self.symtab.lookup(param_token['lexeme'])
                            
                            if symbol_param:
                                symbol_param['initialized'] = True
                                symbol_param['init_pos'] = "Parâmetro"
                                symbol_param['value'] = "Input"
                                
                        if not self.match('DELIMITER', ','):
                            break
                
                self.consume('DELIMITER', ')', "Esperado ')' após os parâmetros.")
                
                self.consume('DELIMITER', '{', "Esperado '{'.")

                has_returned = False
                
                while not self.check('DELIMITER', '}') and not self.is_end_token_list():
                    if has_returned:
                        self.symtab.warnings.append(f"Aviso Semântico [Linha {self.peek_lookahead()['line']}]: Código inalcançável após return.")
                        
                        while not self.check('DELIMITER', '}') and not self.is_end_token_list(): 
                            self.advance() 
                    
                        break 
                    
                    if self.check('KEYWORD', 'return') or self.check('IDENTIFIER', 'return'): 
                        has_returned = True
                        
                    self.statement()
                    
                self.consume('DELIMITER', '}', "Esperado '}'.")
                
                self.symtab.exit_scope()

            else:
                if not self.symtab.declare(var_name, var_type, var_line, var_col):
                    self.semantic_errors.append(f"Erro Semântico [Linha {var_line}]: Variável '{var_name}' já declarada.")
                    
                if self.match('OPERATOR', '='):
                    token_val = self.peek_lookahead() 
                    expr_type = self.expression()
                    
                    if expr_type != 'unknown' and expr_type != var_type and not (var_type == 'float' and expr_type == 'int'):
                        self.semantic_errors.append(f"Erro Semântico [Linha {var_line}]: Tentativa de atribuir '{expr_type}' a '{var_type}'.")
                    
                    symbol = self.symtab.lookup(var_name)

                    if symbol: 
                        symbol['initialized'] = True
                        symbol['init_pos'] = f"{var_line} x {var_col}"

                        if token_val and token_val['class'] in ['INT_LIT', 'FLOAT_LIT', 'STRING_LIT', 'CHAR_LIT']:
                            symbol['value'] = token_val['lexeme']
                        else:
                            symbol['value'] = 'Expr'

                self.consume('DELIMITER', ';', "Esperado ';' após a declaração.")
                
    def block(self):
        self.consume('DELIMITER', '{', "Esperado '{'.")
        self.symtab.enter_scope() 
        has_returned = False
        
        while not self.check('DELIMITER', '}') and not self.is_end_token_list():
            if has_returned:
                self.symtab.warnings.append(f"Aviso Semântico [Linha {self.peek_lookahead()['line']}]: Código inalcançável.")
                
                while not self.check('DELIMITER', '}') and not self.is_end_token_list(): self.advance()
                
                break

            if self.check('KEYWORD', 'return') or self.check('IDENTIFIER', 'return'): has_returned = True
            
            self.statement()
            
        self.consume('DELIMITER', '}', "Esperado '}'.")
        self.symtab.exit_scope()

    def assignment_or_expr(self):
        if self.check('IDENTIFIER'):
            var_token = self.peek_lookahead()
            var_name = var_token['lexeme']
            var_line = var_token['line']
            var_col = var_token['column']
            
            self.advance()
            if self.match('OPERATOR', '=') or self.match('OPERATOR', '+=') or self.match('OPERATOR', '-='):
                token_val = self.peek_lookahead()
                expr_type = self.expression()
                symbol = self.symtab.lookup(var_name)
                
                if not symbol:
                    self.semantic_errors.append(f"Erro Semântico [Linha {var_line}]: '{var_name}' não declarada.")
                
                else:
                    if expr_type != 'unknown' and expr_type != symbol['type'] and not (symbol['type'] == 'float' and expr_type == 'int'):
                        self.semantic_errors.append(f"Erro Semântico [Linha {var_line}]: '{var_name}' recebeu tipo incompatível '{expr_type}'.")
                    
                    if not symbol['initialized']: 
                        symbol['init_pos'] = f"{var_line} x {var_col}"

                    symbol['initialized'] = True
                    symbol['used'] = True 
                    
                    if token_val and token_val['class'] in ['INT_LIT', 'FLOAT_LIT', 'STRING_LIT', 'CHAR_LIT']:
                        symbol['value'] = token_val['lexeme']

                    else:
                        symbol['value'] = 'Expr'
           
            elif self.match('OPERATOR', '++') or self.match('OPERATOR', '--'):
                symbol = self.symtab.lookup(var_name)

                if not symbol:
                     self.semantic_errors.append(f"Erro Semântico [Linha {var_line}]: '{var_name}' não declarada.")
                
                else:
                     symbol['used'] = True

            else:
                self.current -= 1
                self.expression()

        else:
            self.expression()
            
        self.consume('DELIMITER', ';', "Esperado ';' após comando.")

    def if_statement(self):
        self.advance() 
        self.consume('DELIMITER', '(', "Esperado '(' após 'if'.")
        cond_type = self.expression()

        if cond_type != 'unknown' and cond_type not in ['bool', 'int']:
            self.semantic_errors.append(f"Erro Semântico [Linha {self.previous()['line']}]: Condição do if deve ser booleano.")
        
        self.consume('DELIMITER', ')', "Esperado ')'.")
        self.block()

    def for_statement(self):
        self.advance() 
        self.consume('DELIMITER', '(', "Esperado '(' após 'for'.")
        self.symtab.enter_scope() 
        
        if self.check('KEYWORD', 'int') or self.check('KEYWORD', 'float'):
            self.advance()
            var_type = self.previous()['lexeme']
            self.consume('IDENTIFIER', None, "Esperado identificador.")
            var_token = self.previous()
            var_name = var_token['lexeme']
            
            self.symtab.declare(var_name, var_type, var_token['line'], var_token['column'])
            symbol = self.symtab.lookup(var_name)
            
            self.consume('OPERATOR', '=', "Esperado '='.")
            token_val = self.peek_lookahead()
            self.expression()

            if symbol: 
                symbol['initialized'] = True
                symbol['init_pos'] = f"{var_token['line']} x {var_token['column']}"

                if token_val and token_val['class'] in ['INT_LIT', 'FLOAT_LIT']:
                    symbol['value'] = token_val['lexeme']

            self.consume('DELIMITER', ';', "Esperado ';'.")

        else:
            self.assignment_or_expr()
            
        self.expression()
        self.consume('DELIMITER', ';', "Esperado ';'.")
        
        if self.match('IDENTIFIER'):
            var_token = self.previous()
            symbol = self.symtab.lookup(var_token['lexeme'])

            if symbol: 
                symbol['used'] = True
            
            if not (self.match('OPERATOR', '++') or self.match('OPERATOR', '--') or self.match('OPERATOR', '=')):
                self.errors.append("Erro Sintático: Esperado incremento.")
               
                raise SyntaxError()
           
            if self.previous()['lexeme'] == '=': self.expression()
        
        self.consume('DELIMITER', ')', "Esperado ')'.")
        
        self.consume('DELIMITER', '{', "Esperado '{'.")
        has_returned = False

        while not self.check('DELIMITER', '}') and not self.is_end_token_list():
            if has_returned:
                self.symtab.warnings.append(f"Aviso Semântico [Linha {self.peek_lookahead()['line']}]: Código inalcançável.")
                
                while not self.check('DELIMITER', '}') and not self.is_end_token_list(): self.advance()
                
                break

            if self.check('KEYWORD', 'return') or self.check('IDENTIFIER', 'return'): has_returned = True
           
            self.statement()

        self.consume('DELIMITER', '}', "Esperado '}'.")
        self.symtab.exit_scope() 

    def return_statement(self):
        self.advance()
        self.expression()
        self.consume('DELIMITER', ';', "Esperado ';'.")

    ''' EXPRESSION RULES '''

    def expression(self):
        return self.logical()

    def logical(self):
        left_type = self.equality()

        while self.match('OPERATOR', '&&') or self.match('OPERATOR', '||'):
            op, line = self.previous()['lexeme'], self.previous()['line']
            left_type = self.check_type_compatibility(left_type, op, self.equality(), line)
       
        return left_type

    def equality(self):
        left_type = self.relational()
        
        while self.match('OPERATOR', '==') or self.match('OPERATOR', '!='):
            op, line = self.previous()['lexeme'], self.previous()['line']

            left_type = self.check_type_compatibility(left_type, op, self.relational(), line)
        
        return left_type

    def relational(self):
        left_type = self.term()

        while self.match('OPERATOR', '<') or self.match('OPERATOR', '<=') or \
              self.match('OPERATOR', '>') or self.match('OPERATOR', '>='):
            op, line = self.previous()['lexeme'], self.previous()['line']
            left_type = self.check_type_compatibility(left_type, op, self.term(), line)

        return left_type

    def term(self):
        left_type = self.factor()

        while self.match('OPERATOR', '+') or self.match('OPERATOR', '-'):
            op, line = self.previous()['lexeme'], self.previous()['line']
            left_type = self.check_type_compatibility(left_type, op, self.factor(), line)

        return left_type

    def factor(self):
        left_type = self.primary()

        while self.match('OPERATOR', '*') or self.match('OPERATOR', '/'):
            op, line = self.previous()['lexeme'], self.previous()['line']
            left_type = self.check_type_compatibility(left_type, op, self.primary(), line)

        return left_type

    def primary(self):
        if self.match('INT_LIT'): return 'int'
        if self.match('FLOAT_LIT'): return 'float'
        if self.match('STRING_LIT'): return 'string'
        if self.match('CHAR_LIT'): return 'char'
        
        if self.match('IDENTIFIER'):
            var_token = self.previous()
            var_name, var_line, var_col = var_token['lexeme'], var_token['line'], var_token['column']
            symbol = self.symtab.lookup(var_name)

            if self.match('DELIMITER', '('):
                if not self.check('DELIMITER', ')'):
                    while True:
                        self.expression()

                        if not self.match('DELIMITER', ','):
                            break

                self.consume('DELIMITER', ')', "Esperado ')' fechando a chamada de função.")

                if not symbol:
                    self.semantic_errors.append(f"Erro Semântico [Linha {var_line}]: '{var_name}' não declarada.")
                    
                    return 'unknown'
                
                else:
                    symbol['used'] = True

                    return symbol['type']
            
            if not symbol:
                self.semantic_errors.append(f"Erro Semântico [Linha {var_line}]: '{var_name}' não declarada.")
                
                return 'unknown'
            else:
                symbol['used'] = True
                
                if not symbol['initialized']:
                    self.symtab.warnings.append(f"Aviso Semântico [Linha {var_line}]: '{var_name}' utilizada sem valor.")
                
                return symbol['type']
                    
        if self.match('DELIMITER', '('):
            expr_type = self.expression()
            self.consume('DELIMITER', ')', "Esperado ')'.")

            return expr_type
                
        token = self.peek_lookahead()

        if token: self.errors.append(f"Erro Sintático [Linha {token['line']}]: Encontrou '{token['lexeme']}' de forma inesperada.")
        
        raise SyntaxError()