'''
    The Parser takes the list of tokens generated by the Lexer and verifies if they follow the 
    grammatical structure of the language using a Recursive Descent parsing strategy.

        1) Syntactic Matching: Each grammatical rule (declarations, assignments, if/for loops, and 
           expressions) is mapped to a specific method. The parser uses pointers and lookahead functions 
           (peek, check, match) to validate the current token against what is expected by the grammar.
           If valid, it consumes the token and advances.

        2) Error Recovery (Panic Mode): If a token violates the grammatical rules, a SyntaxError is raised. 
           Instead of crashing the entire compiler, the synchronize() method is triggered. It discards 
           problematic tokens until it finds a safe synchronization point (like a semicolon ';' or a 
           statement keyword like 'int', 'if', 'for'), allowing the parser to catch and report multiple 
           syntactic errors in a single run.
    
'''

class SyntaxError(Exception):
    pass

class Parser:
    def __init__(self, tokens):
        self.tokens = tokens
        self.current = 0
        self.errors = []

    def peek_lookahead(self): #lookahead without advancing
        if self.current < len(self.tokens):
            return self.tokens[self.current]
        return None

    def previous(self):
        return self.tokens[self.current - 1]

    def is_end_token_list(self): 
        return self.current >= len(self.tokens)

    def advance(self): #advance pointer and return previous token
        if not self.is_end_token_list():
            self.current += 1
        return self.previous()


    def check(self, token_class, lexeme=None): 
        if self.is_end_token_list():
            return False
        
        token = self.peek_lookahead()
        
        target_class = 'RESERVED_WORD' if token_class == 'KEYWORD' else token_class
        
        if lexeme: #checks if lexeme and class match
            return (token['class'].upper() == token_class.upper() or token['class'].upper() == target_class) and token['lexeme'] == lexeme
       
        return token['class'].upper() == token_class.upper() or token['class'].upper() == target_class

    def match(self, token_class, lexeme=None): 
        if self.check(token_class, lexeme):
            self.advance()
            return True
        
        return False

    def consume(self, token_class, lexeme, message): 
        if self.check(token_class, lexeme):
            return self.advance()
        
        token = self.peek_lookahead()
        
        if token:
            error_msg = f"Erro Sintático [Linha {token['line']}, Col {token['column']}]: Esperava '{lexeme if lexeme else token_class}', mas encontrou '{token['lexeme']}'. {message}"
        else:
            error_msg = f"Erro Sintático: Fim de arquivo inesperado. Esperava '{lexeme if lexeme else token_class}'. {message}"
        
        self.errors.append(error_msg)

        raise SyntaxError()

    def synchronize(self): #try to find synchronization point
        self.advance()

        while not self.is_end_token_list():
            if self.previous()['lexeme'] == ';':
                return
            
            current_token = self.peek_lookahead()

            if current_token and current_token['lexeme'] in ['int', 'float', 'char', 'string', 'bool', 'if', 'for', 'return']:
                return
            
            self.advance()

    def parse(self):
        self.current = 0
        self.errors = []

        while not self.is_end_token_list():  
            try:
                self.statement()

            except SyntaxError:
                self.synchronize()

        return self.errors


    ''' GRAMMAR RULES '''

    def statement(self):
        if self.check('KEYWORD', 'int') or self.check('KEYWORD', 'float') or \
           self.check('KEYWORD', 'char') or self.check('KEYWORD', 'string') or \
           self.check('KEYWORD', 'bool'):
           self.declaration_or_function()

        elif self.check('KEYWORD', 'if'):
            self.if_statement()

        elif self.check('KEYWORD', 'for'):
            self.for_statement()

        elif self.check('KEYWORD', 'return'):
            self.return_statement()

        elif self.check('DELIMITER', '{'):
            self.block()

        else:
            self.assignment_or_expr()

    def declaration_or_function(self):
        self.advance() 
        self.consume('IDENTIFIER', None, "Esperado nome do identificador após o tipo.")
        
        if self.match('DELIMITER', '('):
            self.consume('DELIMITER', ')', "Esperado ')' após os parâmetros da função.")
            self.block() 

        else:
            if self.match('OPERATOR', '='):
                self.expression()

            self.consume('DELIMITER', ';', "Esperado ';' após a declaração.")

    def block(self):
        self.consume('DELIMITER', '{', "Esperado '{' para iniciar bloco.")

        while not self.check('DELIMITER', '}') and not self.is_end_token_list():
            self.statement()

        self.consume('DELIMITER', '}', "Esperado '}' para fechar bloco.")

    def assignment_or_expr(self):
        if self.match('IDENTIFIER'):
            if self.match('OPERATOR', '='):
                self.expression()

            elif self.match('OPERATOR', '++') or self.match('OPERATOR', '--'):
                pass

            else:
                self.errors.append(f"Erro Sintático [Linha {self.previous()['line']}]: Operação inválida para o identificador '{self.previous()['lexeme']}'.")
                raise SyntaxError()
            
        else:
            self.expression()

        self.consume('DELIMITER', ';', "Esperado ';' após comando.")

    def if_statement(self):
        self.advance() 
        self.consume('DELIMITER', '(', "Esperado '(' após 'if'.")
        self.expression()
        self.consume('DELIMITER', ')', "Esperado ')' após condição do 'if'.")
        self.block()

    def for_statement(self):
        self.advance() 
        self.consume('DELIMITER', '(', "Esperado '(' após 'for'.")
        
        if self.check('KEYWORD', 'int') or self.check('KEYWORD', 'float'):
            self.advance()
            self.consume('IDENTIFIER', None, "Esperado identificador no for.")
            self.consume('OPERATOR', '=', "Esperado '=' na inicialização do for.")
            self.expression()
            self.consume('DELIMITER', ';', "Esperado ';' após a inicialização do for.")

        else:
            self.assignment_or_expr()
            
        self.expression()
        self.consume('DELIMITER', ';', "Esperado ';' após condição do for.")
        
        if self.match('IDENTIFIER'):
            if not (self.match('OPERATOR', '++') or self.match('OPERATOR', '--') or self.match('OPERATOR', '=')):
                self.errors.append("Erro Sintático: Esperado incremento ou atribuição na 3ª parte do for.")
                raise SyntaxError()
            
            if self.previous()['lexeme'] == '=':
                self.expression()
        
        self.consume('DELIMITER', ')', "Esperado ')' para fechar o 'for'.")
        self.block()

    def return_statement(self):
        self.advance() 
        self.expression()
        self.consume('DELIMITER', ';', "Esperado ';' após o comando return.")


    ''' EXPRESSION RULES '''

    def expression(self):
        self.logical()

    def logical(self):
        self.equality()

        while self.match('OPERATOR', '&&') or self.match('OPERATOR', '||'):
            self.equality()

    def equality(self):
        self.relational()

        while self.match('OPERATOR', '==') or self.match('OPERATOR', '!='):
            self.relational()

    def relational(self):
        self.term()

        while self.match('OPERATOR', '<') or self.match('OPERATOR', '<=') or \
              self.match('OPERATOR', '>') or self.match('OPERATOR', '>='):
            self.term()

    def term(self):
        self.factor()

        while self.match('OPERATOR', '+') or self.match('OPERATOR', '-'):
            self.factor()

    def factor(self):
        self.primary()

        while self.match('OPERATOR', '*') or self.match('OPERATOR', '/'):
            self.primary()

    def primary(self): 
        if self.match('INT_LIT') or self.match('FLOAT_LIT') or self.match('STRING_LIT') or self.match('CHAR_LIT'):
            return
        
        if self.match('IDENTIFIER'):
            return
        
        if self.match('DELIMITER', '('):
            self.expression()
            self.consume('DELIMITER', ')', "Esperado ')' após expressão.")
            return
            
        token = self.peek_lookahead()

        if token:
            self.errors.append(f"Erro Sintático [Linha {token['line']}, Col {token['column']}]: Esperado valor, variável ou '(', mas encontrou '{token['lexeme']}'.")
        
        raise SyntaxError()